name: afft
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=4.5=1_gnu
  - blas=1.0=mkl
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2021.10.8=ha878542_0
  - certifi=2021.10.8=py37h89c1867_2
  - colorama=0.4.4=pyh9f0ad1d_0
  - cudatoolkit=11.3.1=h2bc3f7f_2
  - ffmpeg=4.3=hf484d3e_0
  - freetype=2.11.0=h70c0345_0
  - giflib=5.2.1=h7b6447c_0
  - gmp=6.2.1=h2531618_2
  - gnutls=3.6.15=he1e5248_0
  - intel-openmp=2021.4.0=h06a4308_3561
  - jpeg=9d=h7f8727e_0
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.35.1=h7274673_9
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.3.0=h5101ec6_17
  - libgomp=9.3.0=h5101ec6_17
  - libiconv=1.15=h63c8f33_5
  - libidn2=2.3.2=h7f8727e_0
  - libpng=1.6.37=hbc83047_0
  - libstdcxx-ng=9.3.0=hd4cf53a_17
  - libtasn1=4.16.0=h27cfd23_0
  - libtiff=4.2.0=h85742a9_0
  - libunistring=0.9.10=h27cfd23_0
  - libuv=1.40.0=h7b6447c_0
  - libwebp=1.2.0=h89dd481_0
  - libwebp-base=1.2.0=h27cfd23_0
  - lz4-c=1.9.3=h295c915_1
  - mkl=2021.4.0=h06a4308_640
  - mkl-service=2.4.0=py37h7f8727e_0
  - mkl_fft=1.3.1=py37hd3c417c_0
  - mkl_random=1.2.2=py37h51133e4_0
  - ncurses=6.3=h7f8727e_2
  - nettle=3.7.3=hbbd107a_1
  - numpy=1.21.2=py37h20f2e39_0
  - numpy-base=1.21.2=py37h79a1101_0
  - olefile=0.46=py37_0
  - openh264=2.1.1=h4ff587b_0
  - openssl=1.1.1n=h7f8727e_0
  - pillow=8.4.0=py37h5aabda8_0
  - pip=21.2.2=py37h06a4308_0
  - python=3.7.11=h12debd9_0
  - python_abi=3.7=2_cp37m
  - pytorch=1.10.1=py3.7_cuda11.3_cudnn8.2.0_0
  - pytorch-mutex=1.0=cuda
  - readline=8.1.2=h7f8727e_1
  - setuptools=58.0.4=py37h06a4308_0
  - six=1.16.0=pyhd3eb1b0_0
  - sqlite=3.37.0=hc218d9a_0
  - tk=8.6.11=h1ccaba5_0
  - torchaudio=0.10.1=py37_cu113
  - torchvision=0.11.2=py37_cu113
  - tqdm=4.64.0=pyhd8ed1ab_0
  - typing_extensions=3.10.0.2=pyh06a4308_0
  - wheel=0.37.1=pyhd3eb1b0_0
  - xz=5.2.5=h7b6447c_0
  - zlib=1.2.11=h7f8727e_4
  - zstd=1.4.9=haebb681_0
  - pip:
    - absl-py==1.0.0
    - aiohttp==3.8.1
    - aiosignal==1.2.0
    - antlr4-python3-runtime==4.8
    - async-timeout==4.0.2
    - asynctest==0.13.0
    - attrs==21.4.0
    - av==9.2.0
    - blessed==1.19.1
    - blessings==1.7
    - cached-property==1.5.2
    - cachetools==5.1.0
    - charset-normalizer==2.0.12
    - click==8.0.4
    - cloudpickle==2.0.0
    - cycler==0.11.0
    - datasets==2.3.2
    - decorator==4.4.2
    - dill==0.3.5.1
    - docker-pycreds==0.4.0
    - einops==0.4.1
    - filelock==3.6.0
    - fonttools==4.33.3
    - frozenlist==1.3.0
    - fsspec==2022.5.0
    - fvcore==0.1.5.post20220512
    - gitdb==4.0.9
    - gitpython==3.1.27
    - google-auth==2.6.6
    - google-auth-oauthlib==0.4.6
    - gpustat==0.6.0
    - grpcio==1.46.3
    - h5py==3.6.0
    - huggingface-hub==0.5.1
    - hydra-core==1.1.1
    - idna==3.3
    - imageio==2.19.2
    - imageio-ffmpeg==0.4.7
    - importlib-metadata==4.11.1
    - importlib-resources==5.4.0
    - inquirer==2.9.2
    - iopath==0.1.9
    - joblib==1.1.0
    - kiwisolver==1.4.2
    - lmdb==1.3.0
    - markdown==3.3.7
    - matplotlib==3.5.2
    - moviepy==1.0.3
    - multidict==6.0.2
    - multiprocess==0.70.13
    - munch==2.5.0
    - networkx==2.6.3
    - numpyencoder==0.3.0
    - nvidia-ml-py3==7.352.0
    - oauthlib==3.2.0
    - omegaconf==2.1.1
    - opencv-python==4.5.5.64
    - packaging==21.3
    - pandas==1.3.5
    - parameterized==0.8.1
    - pathtools==0.1.2
    - portalocker==2.4.0
    - pretrainedmodels==0.7.4
    - proglog==0.1.10
    - promise==2.3
    - protobuf==3.19.4
    - psutil==5.9.0
    - pyarrow==8.0.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pyparsing==3.0.8
    - python-dateutil==2.8.2
    - python-editor==1.0.4
    - pytorchvideo==0.1.5
    - pytz==2021.3
    - pyyaml==6.0
    - readchar==3.0.5
    - regex==2022.4.24
    - requests==2.27.1
    - requests-oauthlib==1.3.1
    - responses==0.18.0
    - rsa==4.8
    - sacremoses==0.0.49
    - scipy==1.7.3
    - seaborn==0.11.2
    - sentry-sdk==1.5.5
    - shortuuid==1.0.8
    - smmap==5.0.0
    - submitit==1.4.2
    - tabulate==0.8.9
    - tensorboard==2.9.0
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - termcolor==1.1.0
    - timm==0.5.4
    - tokenizers==0.12.1
    - transformers==4.18.0
    - urllib3==1.26.8
    - wandb==0.12.10
    - wcwidth==0.2.5
    - werkzeug==2.1.2
    - wget==3.2
    - xxhash==3.0.0
    - yacs==0.1.8
    - yarl==1.7.2
    - yaspin==2.1.0
    - zipp==3.7.0
prefix: /home/haicore-project-kit/on3546/anaconda3/envs/action
